name: my_debts
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_slidable: ^3.1.2
  google_fonts: ^6.3.0
  intl: ^0.20.2
  path: 1.9.0
  pdf: ^3.11.3
  printing: ^5.14.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_logo.png

  fonts:
    - family: Hacen Tunisia
      fonts:
        - asset: assets/fonts/Hacen Tunisia.ttf

    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoCondensed-Light.ttf
          weight: 300
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          weight: 300
